name: Build, Test and Notify

on:
  push:

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile program
        run: g++ salutator.cpp -o hello

      - name: Run unit test
        run: |
          output=$(./hello)
          if [ "$output" != "Hola Mundo" ]; then
            echo "Test failed"
            echo "Expected: Hola Mundo"
            echo "Actual: $output"
            exit 1
          fi
          echo "Test passed"

      - name: Send ntfy notification
        if: success()
        run: |
          curl -H "Title: GitHub Actions" \
               -H "Priority: default" \
               -d "Practica 4. Push realizado correctamente." \
               https://ntfy.sh/devops-itla
